import type { Project, NewsPost, ContactInquiry, ProjectUpdate, AdminUser } from '@/types';

const imagePath = (name: string) => `/assets/images/${name}`;

const now = new Date();
const iso = (daysAgo: number) => new Date(now.getTime() - daysAgo * 86400000).toISOString();

const projectUpdates: Record<string, ProjectUpdate[]> = {
  'proj-001': [
    {
      id: 'upd-001-1',
      projectId: 'proj-001',
      date: '2026-06-10',
      title: 'Structural Framework Complete',
      description: 'Successfully completed the structural concrete framework for all 12 floors ahead of schedule. The team achieved an impressive milestone with zero safety incidents reported throughout the structural phase.',
      image: imagePath('lamed_1.jpg'),
      createdAt: iso(50),
    },
    {
      id: 'upd-001-2',
      projectId: 'proj-001',
      date: '2026-03-22',
      title: 'MEP Installation Progress',
      description: 'Mechanical, electrical, and plumbing installations are now 65% complete. Our specialized subcontractors are working in parallel with finishing teams to optimize the construction timeline.',
      createdAt: iso(130),
    },
    {
      id: 'upd-001-3',
      projectId: 'proj-001',
      date: '2025-12-01',
      title: 'Groundbreaking Ceremony',
      description: 'Official groundbreaking ceremony held with distinguished guests from the Ethiopian Housing Corporation and local government officials. The event marked the beginning of this transformative residential project.',
      image: imagePath('lamed_3.jpg'),
      createdAt: iso(240),
    },
  ],
  'proj-002': [
    {
      id: 'upd-002-1',
      projectId: 'proj-002',
      date: '2026-07-01',
      title: 'Project Kick-off',
      description: 'The official project kick-off meeting was held today with all stakeholders present. Site mobilization and enabling works commence immediately.',
      createdAt: iso(29),
    },
  ],
  'proj-003': [
    {
      id: 'upd-003-1',
      projectId: 'proj-003',
      date: '2026-05-18',
      title: 'Retail Podium Topped Out',
      description: 'The three-level retail podium has been successfully topped out. Construction of the residential tower cores is now underway with excellent progress.',
      image: imagePath('east_mixed.jpg'),
      createdAt: iso(73),
    },
    {
      id: 'upd-003-2',
      projectId: 'proj-003',
      date: '2026-01-30',
      title: 'Foundation Works Complete',
      description: 'All foundation and basement works have been completed. The raft foundation, designed by our structural engineering partners, provides exceptional load-bearing capacity for the multi-tower structure.',
      createdAt: iso(181),
    },
  ],
  'proj-004': [
    {
      id: 'upd-004-1',
      projectId: 'proj-004',
      date: '2026-08-10',
      title: 'Current Status of the Project',
      description: 'The current status of the Entoto Kidane Mihret project demonstrates remarkable progress near completion, with structural integrity solidified, exterior and interior finishes underway for the two 2B+G+5 assembly blocks and residential quarters for 80 monks.',
      image: imagePath('Entoto current status.png'),
      createdAt: iso(15),
    },
    {
      id: 'upd-004-2',
      projectId: 'proj-004',
      date: '2026-07-15',
      title: 'Progress Presentation to Archbishops',
      description: 'The project manager gave a detailed presentation to the Archbishops and religious fathers on the progress of the Entoto Hamer Noah Kidane Mihret project, which is nearing completion and includes two Blocks of 2B+G+5 assembly hall buildings and residential buildings for 80 monks.',
      image: imagePath('Entot geletsa 1.png'),
      createdAt: iso(40),
    },
    {
      id: 'upd-004-3',
      projectId: 'proj-004',
      date: '2026-06-20',
      title: 'Assembly Halls & Monks Residential Blocks Overview',
      description: 'Comprehensive review of the structural progress for the two 2B+G+5 assembly hall blocks and residential quarters accommodating 80 monks, showcasing advanced execution and finishing work.',
      image: imagePath('Entot geletsa 2.png'),
      createdAt: iso(65),
    },
    {
      id: 'upd-004-4',
      projectId: 'proj-004',
      date: '2025-08-30',
      title: 'Main Church Structure Completed',
      description: 'The landmark Entoto Kidane Mihret project structure standing complete with high quality architectural masonry and preservation standards.',
      image: imagePath('Entoto kidanmhiret modified.jpg'),
      createdAt: iso(334),
    },
  ],
  'proj-005': [
    {
      id: 'upd-005-1',
      projectId: 'proj-005',
      date: '2025-11-15',
      title: 'Project Completion',
      description: 'The villa renovation was completed to the highest standards and handed over to a very satisfied client. The final walkthrough confirmed every detail matched the exacting specifications.',
      image: imagePath('shilmat.jpg'),
      createdAt: iso(257),
    },
    {
      id: 'upd-005-2',
      projectId: 'proj-005',
      date: '2025-07-22',
      title: 'Pool & Landscaping Underway',
      description: 'The infinity pool shell is complete and tile work has begun. Landscape contractors are installing mature trees and the hardscaping elements including stone terraces and water features.',
      createdAt: iso(373),
    },
  ],
  'proj-006': [
    {
      id: 'upd-006-1',
      projectId: 'proj-006',
      date: '2025-12-20',
      title: 'Official Reopening Ceremony',
      description: 'The cathedral was officially reopened in a grand ceremony led by the Archdiocese. The congregation marveled at the transformation as the cathedral looked more magnificent than ever.',
      image: imagePath('church.jpg'),
      createdAt: iso(222),
    },
    {
      id: 'upd-006-2',
      projectId: 'proj-006',
      date: '2025-08-05',
      title: 'Dome Reconstruction Complete',
      description: 'The main dome reconstruction has been successfully completed with traditional materials meeting modern engineering standards. The cross was placed atop the dome in a moving ceremony.',
      createdAt: iso(360),
    },
  ],
};

const projects: Project[] = [
  {
    id: 'proj-004',
    title: 'Entoto Kidanemheret Heritage Project',
    status: 'finished',
    type: 'special',
    clientName: 'Ethiopian Orthodox Church',
    contractValue: 45000000,
    startDate: '2024-03-01',
    endDate: '2025-08-30',
    location: 'Addis Ababa, Entoto Mountains',
    coverImage: imagePath('Entoto kidanmhiret modified.jpg'),
    gallery: [
      imagePath('Entoto kidanmhiret modified.jpg'),
      imagePath('Entoto current status.png'),
      imagePath('Entot geletsa 1.png'),
      imagePath('Entot geletsa 2.png'),
    ],
    shortDescription: 'Presentation to the Archbishops on the progress of the Entoto Hamer Noah Kidane Mihret project, nearing completion with two 2B+G+5 assembly blocks and residential quarters for 80 monks.',
    description: 'Presentation to the Archbishops on the progress of the Entoto Hamer Noah Kidane Mihret project, which is nearing completion and includes two Blocks of 2B+G+5 assembly hall buildings and residential buildings for 80 monks.\n\nThe project manager gave a comprehensive explanation and progress review to the Pop, Archbishops, and religious fathers detailing what was accomplished across the assembly halls, specialized facilities, and living quarters.\n\nCurrent Status of the Project: The Entoto Kidane Mihret project is in its advanced final phase, with the primary church structure standing completed and substantial progress on the assembly halls, monastic quarters, and surrounding landscape infrastructure.\n\nKey Project Scope & Highlights:\n• Two Blocks of 2B+G+5 Assembly Hall Buildings: Multi-purpose auditorium, modern acoustic treatment, specialized conference halls, and ecclesiastical administrative suites.\n• Residential Accommodations for 80 Monks: Purpose-built private quarters, study halls, spiritual contemplation spaces, dining halls, and dedicated sanitary facilities.\n• High-Grade Engineering & Heritage Masonry: Robust reinforced concrete substructure and superstructure executed with Grade-1 engineering standards, integrating traditional stone masonry finishes and weather-resilient mountain roofing architecture.\n• Comprehensive Infrastructure: Includes mountain terrain retaining walls, stormwater drainage, water harvesting systems, access roads, and ceremonial outdoor courtyards.',
    updates: projectUpdates['proj-004'],
    featured: true,
    createdAt: iso(1),
    updatedAt: iso(1),
  },
  {
    id: 'proj-007',
    title: 'Fascad Project (EOTC Holy Trinity University Renovation)',
    status: 'under_construction',
    type: 'commercial',
    clientName: 'EOTC Holy Trinity University / Fascad Properties',
    contractValue: 98000000,
    startDate: '2025-10-01',
    location: 'Addis Ababa, 4 Kilo',
    coverImage: imagePath('fascad.jpg'),
    gallery: [
      imagePath('fascad.jpg'),
      imagePath('east_office.jpg'),
    ],
    shortDescription: 'EOTC. Holy Trinity University Renovation Construction Work Located at 4kilo, Addis Ababa.',
    description: 'EOTC. Holy Trinity University Renovation Construction Work Located at 4kilo, Addis Ababa.\n\nThis landmark renovation and modern facade construction project for the Ethiopian Orthodox Tewahedo Church (EOTC) Holy Trinity University is situated in the historic 4 Kilo academic and cultural hub of Addis Ababa. Lamed Construction was entrusted with executing a complete architectural modernization and structural rehabilitation while preserving the historic character and sacred dignity of this esteemed theological institution.\n\nKey Project Scope & Highlights:\n• Complete Facade Modernization: High-durability exterior wall cladding, specialized curtain wall glazing systems, thermal insulation, and architectural exterior lighting designed for long-term aesthetic beauty.\n• Interior & Structural Renovation: Upgrading university lecture halls, seminar rooms, administrative wings, faculty offices, and academic conference spaces with modern finishes and acoustic optimization.\n• Mechanical, Electrical & Plumbing (MEP) Overhaul: Installation of energy-efficient LED electrical systems, high-speed data cabling infrastructure, modernized HVAC ventilation, and compliant fire safety systems.\n• Educational Infrastructure Enhancement: Refurbishment of study libraries, digital research labs, student support areas, and accessible pathways compliant with modern accessibility standards.',
    updates: projectUpdates['proj-007'] || [],
    featured: true,
    createdAt: iso(200),
    updatedAt: iso(40),
  },
  {
    id: 'proj-008',
    title: 'Bethelem Housing (Sidama Diocese Episcopal Residence Complex)',
    status: 'new_contract',
    type: 'residential',
    clientName: 'Sidama Diocese / Bethelem Real Estate Group',
    contractValue: 140000000,
    startDate: '2026-05-01',
    location: 'Sidama Region, Hawassa',
    coverImage: imagePath('Bethelem mo.jpg'),
    gallery: [
      imagePath('Bethelem mo.jpg'),
      imagePath('East_college.jpg'),
    ],
    shortDescription: 'Sidama Diocese Episcopal Residence Complex located at Hawassa.',
    description: 'Sidama Diocese Episcopal Residence Complex located at Hawassa.\n\nCommissioned by the Sidama Diocese, this prestigious residential and administrative complex delivers comprehensive living, pastoral, and administrative facilities located in the scenic city of Hawassa. Designed and executed by Lamed Construction to blend modern residential elegance with functional ecclesiastical governance, the development sets a high benchmark for regional institutional housing.\n\nKey Project Scope & Highlights:\n• Episcopal Dignitary Residence: Luxurious executive suites for the Bishop and visiting dignitaries, featuring expansive meeting halls, reception salons, private prayer rooms, and landscaped gardens.\n• Community & Administrative Wing: Multi-functional office facilities for diocese leadership, registry archives, pastoral counseling rooms, and conference chambers.\n• Monastic & Clergy Residential Units: High-comfort residential apartments equipped with modern kitchens, living areas, energy-efficient plumbing fixtures, and sound-insulated quarters.\n• Sustainable Site Infrastructure: Comprehensive perimeter security fencing, cobblestone internal driveways, solar water heating systems, sustainable stormwater runoff management, and lush native landscaping suited to Hawassa\'s scenic lakeside climate.',
    updates: projectUpdates['proj-008'] || [],
    featured: true,
    createdAt: iso(150),
    updatedAt: iso(20),
  },
  {
    id: 'proj-006',
    title: 'The Cathedral Church of Abchikli Tsirha Tsion St. Mary',
    status: 'finished',
    type: 'special',
    clientName: 'Archdiocese of Addis Ababa & West Gojjam Diocese',
    contractValue: 62000000,
    startDate: '2024-06-01',
    endDate: '2025-12-20',
    location: 'West Gojjam Zone, South Achefer Woreda, Betekihnet, Ethiopia',
    coverImage: imagePath('church.jpg'),
    gallery: [
      imagePath('church.jpg'),
      imagePath('Entoto kidanmhiret modified.jpg'),
    ],
    shortDescription: 'The Cathedral Church of Abchikli Tsirha Tsion St. Mary, the Seat of the Diocese, at the South Achefer Woreda Betekihnet in West Gojjam Zone.',
    description: 'The Cathedral Church of Abchikli Tsirha Tsion St. Mary, the Seat of the Diocese, at the South Achefer Woreda Betekihnet in West Gojjam Zone.\n\nServing as the spiritual seat and central cathedral of the diocese, this monumental religious project stands as an architectural tribute to Ethiopia\'s centuries-old ecclesiastical heritage, built to modern Grade-1 structural durability standards by Lamed Construction.\n\nKey Project Scope & Highlights:\n• Grand Sanctuary & Central Dome: Towering vaulted ceilings, engineered load-bearing dome structure, and hand-carved ornamental arches designed to accommodate thousands of worshippers.\n• Traditional Hand-Chiseled Stonework: Authentic indigenous stone masonry facade paired with reinforced concrete core engineering for seismic and environmental resilience.\n• Sacred Interior Finishes: Specialized sanctuary (Mekdes) partitioning, artisan woodwork, consecrated holy altars, liturgical acoustics, and custom chandelier suspension systems.\n• Diocesan Seat Infrastructure: Includes the Bishop\'s ceremonial throne hall, clergy vestries, theological preparation chambers, treasury vaults, and expansive outdoor ceremonial courtyards for major feast day processions.',
    updates: projectUpdates['proj-006'],
    featured: true,
    createdAt: iso(780),
    updatedAt: iso(222),
  },
  {
    id: 'proj-001',
    title: 'East College',
    status: 'under_construction',
    type: 'residential',
    clientName: 'Ethiopian Housing Corporation',
    contractValue: 125000000,
    startDate: '2025-06-15',
    location: 'Amhara, Debre Marqos, College Area',
    coverImage: imagePath('East_college.jpg'),
    gallery: [
      imagePath('East_college.jpg'),
      imagePath('lamed_1.jpg'),
      imagePath('lamed_3.jpg'),
    ],
    shortDescription: 'G+3 College Building Located in Debre Markos Amhara region.',
    description: 'The East College project is a modern G+3 educational facility located in Debre Markos, Amhara region. Designed and built by Lamed Construction to deliver quality institutional infrastructure, modern lecture halls, laboratories, and administrative wings.\n\nKey Project Scope & Highlights:\n• Multi-Level Academic Complex: G+3 reinforced concrete structure designed with expansive floor plates, earthquake-resistant design, and durable exterior finishes.\n• Advanced Educational Spaces: Fully equipped science laboratories, multi-tier lecture halls, computer training facilities, and an expansive campus library.\n• Administrative & Faculty Suites: Dean and department head offices, faculty meeting lounges, student affairs centers, and secure registrar storage.\n• Robust MEP & Safety Integration: Heavy-duty backup power conduits, fire suppression standpipes, cross-ventilation corridors, and accessible ramps connecting all academic zones.',
    updates: projectUpdates['proj-001'],
    featured: true,
    createdAt: iso(400),
    updatedAt: iso(50),
  },
  {
    id: 'proj-002',
    title: 'G+2 Office Building',
    status: 'new_contract',
    type: 'commercial',
    clientName: 'East Africa Investments PLC',
    contractValue: 280000000,
    startDate: '2026-07-01',
    location: 'Amhara, Debre Markos',
    coverImage: imagePath('east_office.jpg'),
    gallery: [
      imagePath('east_office.jpg'),
      imagePath('fascad.jpg'),
    ],
    shortDescription: 'G+2 Office Building Located in Debre Markos Amhara region.',
    description: 'G+2 Office Building located in Debre Markos, Amhara region. Built with modern commercial standards, flexible office layouts, high quality finishes, and robust structural engineering by Lamed Construction.\n\nKey Project Scope & Highlights:\n• Commercial Corporate Spaces: Designed for corporate headquarters, financial branches, and professional service firms requiring premium commercial presence.\n• Flexible Floor Plates: Open-plan layouts allowing customized tenant partitioning, executive suites, boardrooms, and reception lobbies.\n• Structural & Architectural Excellence: Heavy-duty reinforced concrete columns, modern aluminum composite exterior accents, energy-efficient glazing, and polished porcelain flooring.\n• Complete Utility Network: Dedicated transformer substation setup, high-speed fiber data channel trunking, underground water storage reservoirs, and ample parking facilities.',
    updates: projectUpdates['proj-002'],
    featured: true,
    createdAt: iso(30),
    updatedAt: iso(29),
  },
  {
    id: 'proj-003',
    title: 'G+4 Mixed Use Building',
    status: 'under_construction',
    type: 'mixed_use',
    clientName: 'Merkato Ventures Ltd.',
    contractValue: 195000000,
    startDate: '2025-09-20',
    endDate: '2026-12-31',
    location: 'Amhara, Debre Markos',
    coverImage: imagePath('east_mixed.jpg'),
    gallery: [
      imagePath('east_mixed.jpg'),
      imagePath('East_college.jpg'),
      imagePath('east_office.jpg'),
    ],
    shortDescription: 'G+4 Mixed use Building Located in Debre Markos Amhara region.',
    description: 'G+4 Mixed-use commercial and residential building located in Debre Markos, Amhara region. Combining retail and commercial spaces on the lower floors with comfortable residential units on the upper levels, delivered with Lamed Construction\'s signature quality.\n\nKey Project Scope & Highlights:\n• Integrated Mixed-Use Design: Ground and first-floor commercial retail podium with high pedestrian visibility, complemented by upper-floor modern residential apartments.\n• Structural Engineering: Robust G+4 frame built with Grade-1 concrete mixes, high-yield rebar reinforcement, and cantilevered balcony designs offering panoramic city views.\n• Independent Access & Privacy: Segregated entry lobbies and vertical circulation (stairways and elevator shafts) for commercial visitors and residential occupants.\n• Utilities & Fire Protection: High-capacity water tanks, booster pump stations, individual utility metering for all units, and comprehensive fire exit corridors.',
    updates: projectUpdates['proj-003'],
    featured: true,
    createdAt: iso(310),
    updatedAt: iso(73),
  },
];

const news: NewsPost[] = [
  {
    id: 'news-001',
    title: 'Lamed Construction Honored with Project Completion Certificate',
    excerpt: 'Official Project Completion Certificate awarded by Ethiopian Orthodox Church leadership honoring Lamed Construction for outstanding structural craftsmanship and dedication.',
    content: 'Lamed Construction has been honored with an official Project Completion Certificate awarded by Ethiopian Orthodox Tewahedo Church leadership and the Archbishops & Synod Council.\n\nThe certificate recognizes Lamed Construction\'s exemplary structural craftsmanship, Grade-1 engineering precision, and faithful execution in delivering monumental sanctuary and institutional facilities to the highest quality and safety standards.\n\nLamed Construction\'s Managing Director expressed profound gratitude: "This award belongs to every single member of our team, from our skilled craftsmen on-site to our project managers, structural engineers, and administrative staff. It is a testament to the sacred trust placed in us to deliver landmarks that endure for generations."',
    category: 'Awards',
    coverImage: imagePath('certeficate.jpg'),
    author: 'Dawit Bekele',
    publishedAt: '2026-06-28',
    createdAt: iso(32),
  },
  {
    id: 'news-002',
    title: 'Progress Presentation to Archbishops on Entoto Kidane Mihret Project',
    excerpt: 'The project manager gave a detailed presentation to the Archbishops and religious fathers on the progress of the Entoto Hamer Noah Kidane Mihret project, nearing completion with two 2B+G+5 assembly blocks and residential quarters for 80 monks.',
    content: 'The project manager gave a comprehensive explanation and progress review to the Pop, Archbishops, and religious fathers detailing what was accomplished across the assembly halls, specialized facilities, and living quarters for the Entoto Hamer Noah Kidane Mihret project.\n\nKey Project Scope & Highlights Presented:\n• Two Blocks of 2B+G+5 Assembly Hall Buildings: Multi-purpose auditorium, modern acoustic treatment, specialized conference halls, and ecclesiastical administrative suites.\n• Residential Accommodations for 80 Monks: Purpose-built private quarters, study halls, spiritual contemplation spaces, dining halls, and dedicated sanitary facilities.\n• High-Grade Engineering & Heritage Masonry: Robust reinforced concrete substructure and superstructure executed with Grade-1 engineering standards, integrating traditional stone masonry finishes and weather-resilient mountain roofing architecture.\n• Comprehensive Infrastructure: Includes mountain terrain retaining walls, stormwater drainage, water harvesting systems, access roads, and ceremonial outdoor courtyards.',
    category: 'Projects',
    coverImage: imagePath('Entot geletsa 1.png'),
    author: 'Helen Tesfaye',
    publishedAt: '2026-07-01',
    createdAt: iso(29),
  },
  {
    id: 'news-003',
    title: 'Current Status of the Entoto Kidane Mihret Landmark Project',
    excerpt: 'The Entoto Kidane Mihret project demonstrates remarkable progress near completion, with structural integrity solidified and finishes underway for the two 2B+G+5 assembly blocks and monks residential quarters.',
    content: 'The current status of the Entoto Kidane Mihret project demonstrates remarkable progress in its advanced final phase. The primary church structure stands completed with high quality architectural masonry and preservation standards, while substantial progress continues on the two 2B+G+5 assembly blocks and living quarters for 80 monks.\n\nStructural integrity has been solidified across all blocks, with exterior stone cladding, mountain-resilient roofing, and interior acoustic finishing progressing on schedule. The team continues to maintain Grade-1 engineering precision across every phase of the development.\n\nComprehensive infrastructure including mountain terrain retaining walls, stormwater harvesting, and ceremonial courtyards are also in active progress.',
    category: 'Projects',
    coverImage: imagePath('Entoto current status.png'),
    author: 'Site Operations',
    publishedAt: '2026-05-15',
    createdAt: iso(76),
  },
  {
    id: 'news-004',
    title: 'EOTC Holy Trinity University Facade Modernization & Renovation',
    excerpt: 'EOTC Holy Trinity University Renovation Construction Work located at 4 Kilo, Addis Ababa, delivering complete architectural modernization and structural rehabilitation.',
    content: 'This landmark renovation and modern facade construction project for the Ethiopian Orthodox Tewahedo Church (EOTC) Holy Trinity University is situated in the historic 4 Kilo academic and cultural hub of Addis Ababa.\n\nLamed Construction was entrusted with executing a complete architectural modernization and structural rehabilitation while preserving the historic character and sacred dignity of this esteemed theological institution.\n\nKey Project Scope & Highlights:\n• Complete Facade Modernization: High-durability exterior wall cladding, specialized curtain wall glazing systems, thermal insulation, and architectural exterior lighting designed for long-term aesthetic beauty.\n• Interior & Structural Renovation: Upgrading university lecture halls, seminar rooms, administrative wings, faculty offices, and academic conference spaces with modern finishes and acoustic optimization.\n• Mechanical, Electrical & Plumbing (MEP) Overhaul: Installation of energy-efficient LED electrical systems, high-speed data cabling infrastructure, modernized HVAC ventilation, and compliant fire safety systems.\n• Educational Infrastructure Enhancement: Refurbishment of study libraries, digital research labs, student support areas, and accessible pathways compliant with modern accessibility standards.',
    category: 'Projects',
    coverImage: imagePath('fascad.jpg'),
    author: 'Project Department',
    publishedAt: '2026-04-22',
    createdAt: iso(99),
  },
  {
    id: 'news-005',
    title: 'Sidama Diocese Episcopal Residence Complex in Hawassa',
    excerpt: 'Sidama Diocese Episcopal Residence Complex located at Hawassa, delivering comprehensive living, pastoral, and administrative facilities.',
    content: 'Commissioned by the Sidama Diocese, this prestigious residential and administrative complex delivers comprehensive living, pastoral, and administrative facilities located in the scenic city of Hawassa.\n\nDesigned and executed by Lamed Construction to blend modern residential elegance with functional ecclesiastical governance, the development sets a high benchmark for regional institutional housing.\n\nKey Project Scope & Highlights:\n• Episcopal Dignitary Residence: Luxurious executive suites for the Bishop and visiting dignitaries, featuring expansive meeting halls, reception salons, private prayer rooms, and landscaped gardens.\n• Community & Administrative Wing: Multi-functional office facilities for diocese leadership, registry archives, pastoral counseling rooms, and conference chambers.\n• Monastic & Clergy Residential Units: High-comfort residential apartments equipped with modern kitchens, living areas, energy-efficient plumbing fixtures, and sound-insulated quarters.\n• Sustainable Site Infrastructure: Comprehensive perimeter security fencing, cobblestone internal driveways, solar water heating systems, sustainable stormwater runoff management, and lush native landscaping suited to Hawassa\'s scenic lakeside climate.',
    category: 'Projects',
    coverImage: imagePath('Bethelem mo.jpg'),
    author: 'Hawassa Regional Office',
    publishedAt: '2026-06-10',
    createdAt: iso(50),
  },
  {
    id: 'news-006',
    title: 'East College G+3 Academic Complex in Debre Markos',
    excerpt: 'G+3 College Building Located in Debre Markos Amhara region, designed and built to deliver quality institutional infrastructure, lecture halls, and laboratories.',
    content: 'The East College project is a modern G+3 educational facility located in Debre Markos, Amhara region. Designed and built by Lamed Construction to deliver quality institutional infrastructure, modern lecture halls, laboratories, and administrative wings.\n\nKey Project Scope & Highlights:\n• Multi-Level Academic Complex: G+3 reinforced concrete structure designed with expansive floor plates, earthquake-resistant design, and durable exterior finishes.\n• Advanced Educational Spaces: Fully equipped science laboratories, multi-tier lecture halls, computer training facilities, and an expansive campus library.\n• Administrative & Faculty Suites: Dean and department head offices, faculty meeting lounges, student affairs centers, and secure registrar storage.\n• Robust MEP & Safety Integration: Heavy-duty backup power conduits, fire suppression standpipes, cross-ventilation corridors, and accessible ramps connecting all academic zones.',
    category: 'Projects',
    coverImage: imagePath('East_college.jpg'),
    author: 'Debre Markos Branch',
    publishedAt: '2026-03-18',
    createdAt: iso(134),
  },
];

const inquiries: ContactInquiry[] = [
  {
    id: 'inq-001',
    name: 'Tesfaye Mekonnen',
    email: 'tesfaye.m@example.com',
    phone: '+251 911 234 567',
    service: 'Residential',
    message: 'I would like to discuss building a custom family home in the Lebu area. I have a 500 sqm plot and would love to hear about your residential construction services and process.',
    status: 'unread',
    createdAt: iso(8),
  },
  {
    id: 'inq-002',
    name: 'Sara Ahmed',
    email: 'sara.ahmed@example.com',
    phone: '+251 911 987 654',
    service: 'Commercial',
    message: 'Our company is looking for a contractor for our new 5-story office building in the Meskel Square area. Please send me more information about your commercial project experience and capabilities.',
    status: 'read',
    createdAt: iso(12),
  },
];

const admin: AdminUser = {
  id: 'admin-001',
  email: 'admin@lamed.com',
  name: 'Lamed Admin',
  passwordHash: '$2a$10$rMQj3VrqH8gGkzFwBk7EeeYI5j8qPq9s0YHkQqH1oXoXqH1oXoXoX',
};

import type { Project, NewsPost, ContactInquiry, ProjectUpdate, AdminUser, Certificate } from '@/types';

const certificates: Certificate[] = [
  {
    id: 'cert-001',
    title: 'Project Completion Certificate',
    description: 'Official Project Completion Certificate awarded by Ethiopian Orthodox Church leadership honoring Lamed Construction for outstanding structural craftsmanship and successful project completion.',
    image: imagePath('certeficate.jpg'),
    issuer: 'Ethiopian Orthodox Tewahedo Church',
    year: '2024',
    createdAt: iso(100),
  },
  {
    id: 'cert-002',
    title: 'Project Completion Certificate',
    description: 'Project Completion and Dedication Certificate presented to Lamed Construction upon the successful finalization, ceremonial blessing, and handover of sanctuary buildings.',
    image: imagePath('certeficate2.jpg'),
    issuer: 'Archbishops & Synod Council',
    year: '2023',
    createdAt: iso(200),
  },
  {
    id: 'cert-003',
    title: 'Project Visit & Presentation',
    description: 'Official site visit and progress presentation ("Entoto Geletsa") delivered to the Archbishops and religious fathers, reviewing ongoing progress on the Entoto Kidane Mihret 2B+G+5 assembly halls and residential quarters for 80 monks.',
    image: imagePath('Entot geletsa 1.png'),
    issuer: 'Entoto Kidane Mihret Project Leadership',
    year: '2025',
    createdAt: iso(300),
  },
];

export default {
  projects,
  news,
  inquiries,
  certificates,
  admin,
};

export { projects, news, inquiries, certificates, admin };
export type { Project, NewsPost, ContactInquiry, ProjectUpdate, AdminUser, Certificate };
